### ISSUE TITLE
AD authentication fails due to database error - Default enabled strict mode?

### ISSUE THREAD

**Issue by SoerenBusse** [imedias/glados#108]
We're using Active Directory as an authentication provider for Glados. The "Test Authentication" tool within the admin backend works absolutly fine. However the "normal" login form throws an database error.

```
Next yii\db\Exception: SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value
The SQL being executed was: INSERT INTO `user` (`type`, `identifier`, `username`) VALUES ('88804cf4-26ee-40fd-85f9-9741b0379f1f', 'c753157e-0add-4013-878b-b264c33279e6', 'Username') in /usr/share/yii2/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /usr/share/yii2/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `us...')
#1 /usr/share/yii2/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('INSERT INTO `us...')
#2 /usr/share/yii2/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /usr/share/yii2/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('user', Array)
#4 /usr/share/yii2/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 /usr/share/yii2/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#6 /usr/share/glados/models/UserAuth.php(44): yii\db\BaseActiveRecord->save()
#7 /usr/share/glados/models/LoginForm.php(100): app\models\UserAuth::findByCredentials('Username', 'VERYSECRETPASSWORD')
#8 /usr/share/glados/models/LoginForm.php(54): app\models\LoginForm->getUserAuth()
```
When looking at the source code the `password` field is never set's explicitly. 
https://github.com/imedias/glados/blob/3a63ce584a7793b43f8f6c6c18fefbb619a2dea3/models/UserAuth.php#L31-L49
This works absolutly fine when the user already exists in the local database when using the "Local Authenticiation". In this case the user object does contain the password already and the `save` succeedes. However when the "AD Authentication" is used a new User object will be created without having the password field set. In this case the following cite of "MySQL strict mode" comes into play:

> A value is missing when a new row to be inserted does not contain a value for a non-NULL column that has no explicit DEFAULT clause in its definition.

Looking at the `user` table schema the password field is a "non-NULL" field and has no explicit default value. Because strict mode is enabled by default this case throws the error mentioned above.

![image](https://user-images.githubusercontent.com/7796567/107878300-d96dbd00-6ed1-11eb-9cce-f4a4e1767b31.png)

**Solution:**
Do you have developed the glados server with strict mode in mind? Then we should address this issue by setting the password to an empty string when the user object does not contain an password on the PHP side. Otherwise the strict mode should be  disabled when using the provided .deb packages and the manual installation should contain instructions how to disable strict mode.

**Comment by chaoos** [comment]
Hi Soeren

The reason why the "Test Authentication" tool works is, because it creates no users in the database.

Glados is developed with strict mode in mind. When switching from mysql (debian9) to a newer version of mariadb (debian10) an error concerning this was fixed. The password field slipped through as it seems, thanks for pointing that out! The problem is solved (see commit https://github.com/imedias/glados/commit/22a91cc648f4c79b54543f980e028ff17a3cccde). This will be applied in the database migration of the next release version 1.0.9.

In the meantime please, disable strict mode or change the password field to an empty string default value.

Regards
Roman
