### ISSUE TITLE
"Hand-in exam" .desktop file is not trusted by gnome3

### ISSUE THREAD

**Issue by chaoos** [imedias/glados#35]

**Comment by THS-on** [comment]
This can be fixed by marking the .desktop file as an executable with chmod +x.

gio info "MYDEKSTOPFILE" should return `access::can-execute: TRUE` and `unix::mode: 33261`

**Comment by chaoos** [comment]
@THS-on The file has these properties and is exectable. The problem is, that gnome3 (in contrast to gnome2) has a database with "trusted" .desktop files. Once the file was executed and the appearing dialog was accepted, the file is trusted. 
![grafik](https://user-images.githubusercontent.com/2538562/43138132-34728ad4-8f4e-11e8-961a-52ac6951c11e.png)
