### ISSUE TITLE
Is this project named after the character from the "Portal" game series?

### ISSUE THREAD

**Issue by das-g** [imedias/glados#36]
[![](https://upload.wikimedia.org/wikipedia/en/b/bf/Glados.png)](https://en.wikipedia.org/wiki/GLaDOS)

[At](https://github.com/imedias/glados/blame/49c6b474c0420139d5642a608b04addbaf0e9a9b/howtos/deb-install.md#L3) [some](https://github.com/imedias/glados/blame/c51f644b07b5b7e17e568566f82f1fdb1944e9e8/howtos/manual-install.md#L3) [places](https://github.com/imedias/glados/blob/4749d4914464328ada5562fcc63d9850fd46e83a/views/layouts/main.php#L63), it's even spelled "GLaDOS" &hellip;

**Comment by chaoos** [comment]
@das-g Yes, since GLaDOS in the portal series has the habit to "test" the test subjects and providing harder and harder tests (exams), it was an ironic choice for an exam server providing exams, and I couldn't resist :-)

**Comment by das-g** [comment]
Thanks for the answer!

(Not sure whether GLaDOS is the association you'd want to invoke in pupils/students (which might be a positive association if they put themselves in the role of the player, or a rather not-so-positive one if they put themselves in the role of the playable character, Chell), but that'd be a separate issue, so I'm closing this one.)

> and I couldn't resist

Well, you do what you must, because you can. :wink:
