### ISSUE TITLE
ldap connection to ad

### ISSUE THREAD

**Issue by schbn** [imedias/glados#59]
it would be great if users could authenticate with their ad account.

**Comment by chaoos** [comment]
This work is in progress.

**LDAP still TODO**

* [ ] auth model
  * [ ] id as hash/uuid (auto generated)
  * [ ] sync() in saveConfigFile()
* [ ] user migration
  * [ ] apply to selection
  * [ ] select type
* [ ] user table
  * [ ] type as number (0 => local, hash => auth method)
* [ ] authentication via binduser that browses the ldap
* [ ] remove filter & sort in auth index view
* [ ] descriptions / attribute hints of all involved fields
* [ ] documentation with examples
* [ ] new dependency php-ldap
* [ ] auth.php and auth.php.bak must be writable by webserver user (www-data)
* [ ] remove auth from params.php
