### ISSUE TITLE
ZIP-file not shown on desktop

### ISSUE THREAD

**Issue by sm8ps** [imedias/glados#65]
Using Prüfungsstick based on Lernstick version 2019-06-10, I created a ZIP-file containing a single text file that is attached to the exam. The content is nowhere visible on the exam desktop.

**Comment by chaoos** [comment]
Does the ZIP-file have the corresponding directory structure? (See [Manual - Create a zip-file as exam file](https://github.com/imedias/glados/blob/master/howtos/create-zip-exam-file.md)).

If you want files to appear on the desktop, they must be placed in `/home/user/Desktop`, where the path is localised. If your Lernstick is in German, the path would then be `/home/user/Schreibtisch`.

**Comment by sm8ps** [comment]
Oops, sorry! TLDR was the cause of this mistake. I thought that files would automatically be placed *under* /home/user.

BTW, what is the use case for adding arbitrary files (presumably only with user credentials) anywhere into the file system?
