### ISSUE TITLE
Icon Finish Exam not on desktop

### ISSUE THREAD

**Issue by sm8ps** [imedias/glados#68]
Using Prüfungsstick based on Lernstick version 2019-06-10, the Finish Exam icon is neither in the "ribbon" among the preferred applications on the left side nor on the desktop. The welcome text to the exam explicitly says to "doubleclick the icon at the desktop to finish the exam".
The desktop folder under $HOME indeed is empty. In the primary phase, there is, however, a search_exam_server.desktop on the desktop.
I hope this is the right repository for this bug!

**Comment by chaoos** [comment]
This is fixed and will be in the next version of glados (1.0.6) coming soon. The welcome text has also changed with an explanation, according to the new method of handing in exams.

**Comment by sm8ps** [comment]
Good to know, thanks!
